# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: poc-python3-using-layers # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${file(config.json):region}

# we need connection to our database and we deploy database at postgres aurora, so we need define vpc
  vpc: ${file(config.json):vpc}

# you can add deployment bucket, in our case, we just want to deploy to specific bucket
# note: you should create bucket first
  deploymentBucket:
    name: ${file(config.json):deploymentBucket-name} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: ${file(config.json):deploymentBucket-serverSideEncryption} # when using server-side encryption

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements: ${file(config.json):iamRoleStatements}

# you can define service wide environment variables here
  environment:
    db_string: ${file(config.json):PG_CONNECTION}

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
    layers: ${file(config.json):layers1}

